version: "3.12"

volumes:
  pg_data:

services:

  postgres:
    image: postgres:13
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 5

  backend:
    build:
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - postgres
    command: >
      sh -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
