"""Initial migration

Revision ID: 5dc4cdcd4662
Revises: 
Create Date: 2024-10-25 17:00:20.641624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dc4cdcd4662'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('death_date', sa.DateTime(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_created_at'), 'author', ['created_at'], unique=False)
    op.create_index(op.f('ix_author_updated_at'), 'author', ['updated_at'], unique=False)
    op.create_table('tag',
    sa.Column('title', sa.String(length=55), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_tag_created_at'), 'tag', ['created_at'], unique=False)
    op.create_index(op.f('ix_tag_updated_at'), 'tag', ['updated_at'], unique=False)
    op.create_table('author_tags',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('author_id', 'tag_id', 'id')
    )
    op.create_index(op.f('ix_author_tags_created_at'), 'author_tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_author_tags_updated_at'), 'author_tags', ['updated_at'], unique=False)
    op.create_table('book',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('genre', sa.String(length=150), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_created_at'), 'book', ['created_at'], unique=False)
    op.create_index(op.f('ix_book_updated_at'), 'book', ['updated_at'], unique=False)
    op.create_table('book_tags',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'tag_id', 'id')
    )
    op.create_index(op.f('ix_book_tags_created_at'), 'book_tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_book_tags_updated_at'), 'book_tags', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_tags_updated_at'), table_name='book_tags')
    op.drop_index(op.f('ix_book_tags_created_at'), table_name='book_tags')
    op.drop_table('book_tags')
    op.drop_index(op.f('ix_book_updated_at'), table_name='book')
    op.drop_index(op.f('ix_book_created_at'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_author_tags_updated_at'), table_name='author_tags')
    op.drop_index(op.f('ix_author_tags_created_at'), table_name='author_tags')
    op.drop_table('author_tags')
    op.drop_index(op.f('ix_tag_updated_at'), table_name='tag')
    op.drop_index(op.f('ix_tag_created_at'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_author_updated_at'), table_name='author')
    op.drop_index(op.f('ix_author_created_at'), table_name='author')
    op.drop_table('author')
    # ### end Alembic commands ###
